RMI-PACTA/pacta.loanbook

README.Rmd
README.md

closes #7 
closes #6 
note: still not worried about the checks, they will be tackled with the actual content later

use logo and badges

---

.github/workflows/pr-preview-pkgdown.yaml

closes #13 
- gains GH action to preview the pkgdown site on any PR

add gh action for reviewing pkgdown site on pull requests

---

vignettes/cookbook_running_the_analysis.Rmd

increase the width of output in Running the Analysis

---

vignettes/cookbook_running_the_analysis.Rmd

add company level SDA targets explainer to Running the Analysis

---

vignettes/cookbook_running_the_analysis.Rmd

remove overwrite matches explainer from Running the Analysis

---

vignettes/cookbook_preparatory_steps.Rmd
vignettes/cookbook_running_the_analysis.Rmd

link to data dictionaries where appropriate

---

vignettes/cookbook_preparatory_steps.Rmd

get apropriate columns for sda scenario file

---

man/pacta.loanbook-package.Rd

update docs for new contributor

---

R/conflicts.R
tests/testthat/_snaps/conflicts.md

- resolves #12 
now shows the message "✔ no conflicts found" when no conflicts are found
note: the weird stuff below is the PACTA logo that doesn't render properly here
``` r
library(pacta.loanbook)
#> ── Attaching core pacta.loanbook packages ───────── pacta.loanbook 0.0.0.9000 ──
#> ✔ r2dii.analysis 0.4.0.9004     ✔ r2dii.match    0.3.0.9002
#> ✔ r2dii.data     0.6.0.9000     ✔ r2dii.plot     0.4.0.9001
#> ── Conflicts ───────────────────────────────────── pacta_loanbook_conflicts() ──
#> ✔ no conflicts found
#> [38;5;88m __[39m[38;5;124m__[39m[38;5;160m   [39m[38;5;203m _[39m[38;5;209m__[39m[38;5;216m___[39m[38;5;223m  [39m[38;5;230m___[39m[38;5;231m_ [39m[38;5;231m  [39m[38;5;253m __[39m[38;5;195m__[39m[38;5;153m__ [39m[38;5;117m …
```

display an appropriate message when no conflicts are found

---

vignettes/cookbook_running_the_analysis.Rmd

add instructions to write results to CSV

---

.github/workflows/R-CMD-check-CRAN-incoming.yaml

since a push to main does not have a comment thread to post on

only find and post comment if run on a PR

---

.github/workflows/R-CMD-check-CRAN-incoming.yaml
.github/workflows/pr-preview-pkgdown.yaml

identify pr preview comment so other actions don't overwrite it

---

R/zzz.R

make startup logo suppressible

---

vignettes/cookbook_interpretation.Rmd

remove Cookbook dependency on {rlang}

---

vignettes/cookbook_interpretation.Rmd

remove Cookbook dependency on {purrr}

---

_pkgdown.yml
vignettes/data_classification.Rmd

rename Classification to Sector Classification

---

vignettes/cookbook_preparatory_steps.Rmd

add necessary columns for manual sector classifications to cookbook

---

vignettes/cookbook_preparatory_steps.Rmd

document columns in misclassified loans CSV

---

_pkgdown.yml
vignettes/data_outputs.Rmd

rename Outputs menu item to PACTA outputs

---

_pkgdown.yml

move sit.rep link into Packages menu

---

_pkgdown.yml

promote cookbook to first menu item

---

README.Rmd
README.md

Just getting a bit more precise with what this package enables. 
No associated issue.

docs: re-word README

---

vignettes/articles/cookbook_running_the_analysis.Rmd

mention the Preparatory Steps chapter

---

vignettes/articles/cookbook_preparatory_steps.Rmd

specify dev install as an alternative

---

vignettes/articles/cookbook_running_the_analysis.Rmd

fix bullet points not rendering

---

vignettes/articles/cookbook_preparatory_steps.Rmd

list all required inputs up front

---

vignettes/articles/cookbook_running_the_analysis.Rmd

remove duplication of "a note"

---

vignettes/articles/cookbook_running_the_analysis.Rmd

remove description of using `rev()` as a priority strategy

---

vignettes/articles/cookbook_preparatory_steps.Rmd

note about analyzing multiple loan books

---

vignettes/articles/cookbook_running_the_analysis.Rmd

aligning matching steps with section headers

---

vignettes/articles/cookbook_running_the_analysis.Rmd

demonstrate with `id_loan` instead of `id_2dii`

---

DESCRIPTION
man/pacta.loanbook-package.Rd

remove single quotes from PACTA

---

DESCRIPTION
man/pacta.loanbook-package.Rd

add link to reference in Description

---

DESCRIPTION

remove `mockr` from Suggests

---

DESCRIPTION
vignettes/articles/cookbook_running_the_analysis.Rmd

replace `glue::glue()` with `cli::format_inline()`

---

vignettes/articles/cookbook_overview.Rmd

add "with no or limited support from RMI"

---

vignettes/articles/cookbook_interpretation.Rmd

improve "benchmark region's"

---

DESCRIPTION
NEWS.md

closes #197 
- bumps version number to dev version 0.1.0.9000

Increment version number to 0.1.0.9000

---

NEWS.md
R/update.R

fix `pacta_loanbook_deps()`

---

vignettes/articles/cookbook_preparatory_steps.Rmd

since pkgdown does not auto link datasets

link to `sector_classifications` description

---

vignettes/articles/cookbook_running_the_analysis.Rmd

closes Monday ticket. https://rmi.monday.com/boards/8225089626/pulses/8872839202
- adds a table showing the standard pairing of sectors, technologies, and corresponding calculation approaches before diving into the individual approaches

add table that shows sector-technology pairing

---

vignettes/articles/cookbook_running_the_analysis.Rmd

closes Monday ticket: https://rmi.monday.com/boards/8225089626/pulses/8872829721
closes Monday ticket: https://rmi.monday.com/boards/8225089626/pulses/8872832740
- adds code that allows users to optionally display values in the PACTA visualizations
- displays all values for the tech mix chart
- displays the final values for the volume trajectory and the EI charts

Show percentage in plot

---

man/pacta.loanbook-package.Rd

update docs with ROR ID

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md

bump minimum R version to 4.1

---

NEWS.md
man/prep_emission_intensity.Rd
man/prep_techmix.Rd
man/prep_trajectory.Rd
man/scale_colour_r2dii.Rd
man/scale_colour_r2dii_sector.Rd
man/scale_colour_r2dii_tech.Rd
man/scale_fill_r2dii.Rd
man/scale_fill_r2dii_sector.Rd
man/scale_fill_r2dii_tech.Rd
man/target_sda.Rd
man/theme_2dii.Rd

- related #253 
In prep for 0.1.1, update news and update docs (which are inherited from new versions of r2dii pkgs)

prep for 0.1.1
